title: Shoumik Sharar Chowdhury
logo: /assets/img/img.png
description: CS Masters student and Research Assistant at the University of Houston
show_downloads: true
google_analytics: UA-109993855-1
email: mailto:hello@shoumikchow.com
linkedin: /linkedin
twitter: /twitter
github: /github
theme: jekyll-theme-minimal
pagelist:
    -
      title: Experience
      url: pages/experience.html
    -
      title: Research
      url: pages/research.html
    -
      title: Projects
      url: pages/projects.html
    -
      title: About
      url: pages/about.html

plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME