title: Shoumik Sharar Chowdhury
logo: /assets/img/img.png
description: CS Masters student and Research Assistant at the University of Houston
show_downloads: true
google_analytics: UA-109993855-1
email: mailto:hello@shoumikchow.com
linkedin: https://linkedin.com/in/shoumikchow
twitter: https://twitter.com/shoumikchow
theme: jekyll-theme-minimal
pagelist:
    -
      title: Research
      url: pages/research.html
    -
      title: Experience
      url: pages/experience.html
    -
      title: About me
      url: pages/about-me.html
plugins:
    - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME